version: '3.8'

services:
  db:
    image: postgres
    container_name: postgres-weatherapp-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: weatherapp_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - v-network

  weathermonitoring-app:
    build: .
    ports:
      - "8000:8000"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/weatherapp_db
      SPRING_DATASOURCE_USERNAME: xxxxxxx
      SPRING_DATASOURCE_PASSWORD: xxxxxxx
    depends_on:
      - db
    networks:
      - v-network


networks:
  v-network:
    driver: bridge

volumes:
  postgres-data:
